#!/bin/bash
COLOR1='\033[0;35m'
NC='\e[0m'
MYIP=$(wget -qO- ipinfo.io/ip);
CEKEXPIRED () {
    today=$(date -d +1day +%Y-%m-%d)
    Exp1=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | grep $MYIP | awk '{print $3}')
    if [[ $today < $Exp1 ]]; then
    echo -e "\e[32mSTATUS SCRIPT AKTIF...\e[0m"
    else
    echo -e "\e[31mSCRIPT ANDA EXPIRED!\e[0m";
    exit 0
fi
}
IZIN=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | awk '{print $4}' | grep $MYIP)
if [ $MYIP = $IZIN ]; then
echo -e "\e[32mPermission Accepted...\e[0m"
CEKEXPIRED
else
echo -e "\e[31mPermission Denied!\e[0m";
exit 0
fi
clear
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "                  ⚡ BANDWITH MONITORING ⚡"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "   ${COLOR1}[01]${NC} • Penggunaan Setiap 5 Menit"
echo -e "   ${COLOR1}[02]${NC} • Penggunaan Setiap Jam"
echo -e "   ${COLOR1}[03]${NC} • Penggunaan Setiap Hari"
echo -e "   ${COLOR1}[04]${NC} • Penggunaan Setiap Bulan"
echo -e "   ${COLOR1}[05]${NC} • Penggunaan Secara Live"
echo -e ""
echo -e "   ${COLOR1}[00]${NC} • GO BACK${NC}                          "
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "               ⚡ POWERED BY SCRIPT PREMIUM ⚡"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
read -p " Select menu :  "  opt
echo -e ""
case $opt in
1) clear ; vnstat -5 ;;
2) clear ; vnstat -h ;;
3) clear ; vnstat -d ;;
4) clear ; vnstat -m ;;
5) clear ; vnstat -l ;;
0) clear ; menu ;;
*) clear ; cek-bandwidth ;;
esac