#!/bin/bash
# =========================================
NC='\e[0m'
MYIP=$(wget -qO- ipinfo.io/ip);
CEKEXPIRED () {
    today=$(date -d +1day +%Y-%m-%d)
    Exp1=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | grep $MYIP | awk '{print $3}')
    if [[ $today < $Exp1 ]]; then
    echo -e "\e[32mSTATUS SCRIPT AKTIF...\e[0m"
    else
    echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "$green                    ⚡ INFORMASI SCRIPT ⚡ $NC"
    echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "$red             MASA AKTIF SCRIPT ANDA SUDAH BERAKHIR $NC"
    echo -e "$green        SILAHKAN PERBRUI LISENSI ANDA TERLEBIH DAHULU $NC"
    echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "$tyblue                       KONTAK REGISTRASI $NC"
    echo -e "$tyblue                    WhatsApp: 087749311100 $NC"
    echo -e "$tyblue                    Telegram: @Mass_Alfin $NC"
    echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "$green                ⚡ POWERED BY SCRIPT PREMIUM ⚡ $NC"
    echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "  Press any key to Exit"
    exit 0
fi
}
IZIN=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | awk '{print $4}' | grep $MYIP)
if [[ $MYIP = $IZIN ]]; then
echo -e "\e[32mPermission Accepted...\e[0m"
clear
CEKEXPIRED
else
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "$green                    ⚡ INFORMASI SCRIPT ⚡ $NC"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "$red                      PERIZINAN DITOLAK $NC"
echo -e "$tyblue              SCRIPT BELUM BISA INSTAL DI VPS ANDA $NC"
echo -e "$green          SILAHKAN LAKUKAN REGISTRASI TERLEBIH DAHULU $NC"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "$tyblue                       KONTAK REGISTRASI $NC"
echo -e "$tyblue                    WhatsApp: 087749311100 $NC"
echo -e "$tyblue                    Telegram: @Mass_Alfin $NC"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "$green                ⚡ POWERED BY SCRIPT PREMIUM ⚡ $NC"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -n 1 -s -r -p "  Press any key to Exit"
echo ""
exit 0
fi
clear
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"

trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let tra=$trx/2
ssx=$(grep -c -E "^## " "/etc/xray/config.json")
let ssa=$ssx/2
COLOR1='\033[0;35m'
COLOR2='\033[0;39m'
clear
# // Exporting Language to UTF-8
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'
export LC_CTYPE='en_US.utf8'

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
export Server_URL="autosc.me/aio"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="XdrgVPN"

# // Root Checking
if [ "${EUID}" -ne 0 ]; then
                echo -e "${EROR} Please Run This Script As Root User !"
                exit 1
fi
tomem="$(free | awk '{print $2}' | head -2 | tail -n 1 )"
usmem="$(free | awk '{print $3}' | head -2 | tail -n 1 )"
cpu1="$(mpstat | awk '{print $4}' | head -4 |tail -n 1)"
cpu2="$(mpstat | awk '{print $6}' | head -4 |tail -n 1)"
freq=$(awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo)
cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo)
persenmemori="$(echo "scale=2; $usmem*100/$tomem" | bc)"
persencpu="$(echo "scale=2; $cpu1+$cpu2" | bc)"
# // Exporting IP Address
export MYIP=$( curl -s https://ipinfo.io/ip/ )
Name=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | grep $MYIP | awk '{print $2}')
Exp=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | grep $MYIP | awk '{print $3}')
Mulai=$(curl -sS https://raw.githubusercontent.com/MaddXD/izinkanaku/main/ip | grep $MYIP | awk '{print $6}')

# // nginx
nginx=$( systemctl status nginx | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $nginx == "running" ]]; then
    status_nginx="${GREEN}ON${NC}"
else
    status_nginx="${RED}OFF${NC}"
fi

# // xray
nginx=$( systemctl status xray | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $nginx == "running" ]]; then
    status_xray="${GREEN}ON${NC}"
else
    status_xray="${RED}OFF${NC}"
fi

# // SSH Websocket Proxy
xray=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
if [[ $xray == "running" ]]; then
    status_ssh="${GREEN}ON${NC}"
else
    status_ssh="${RED}OFF${NC}"
fi

clear
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "                         ⚡ INFO VPS ⚡                 \E[0m"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " • Operating System    = $(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')"
echo -e " • Cpu Frequency       =$freq Mhz"
echo -e " • Cpu Model           =$cname"
echo -e " • Current Time        = $( date -d "0 days" +"%d-%m-%Y | %X" )"
echo -e " • Current Domain      = $( cat /etc/xray/domain )"
echo -e " • Server IP           = $MYIP"
echo -e " • ISP                 = $(cat /root/.isp)${NC}"
echo -e " • Server Resource     = RAM = $persenmemori% | CPU = $persencpu%"
echo -e " • Clients Name        = $Name"
echo -e " • Started Lisensi     = $Mulai"
echo -e " • Expired Lisensi     = $Exp"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "   ${COLOR2}[ SSH WebSocket${NC}: ${status_ssh} ]     [ NGINX${NC}: ${status_nginx} ]     [ XRAY${NC}: ${status_xray} ]"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "$COLOR1   \033[0m ${BOLD}${YELLOW}SSH      VMESS        VLESS       TROJAN        SHADSOC$NC  "
echo -e "$COLOR1   \033[0m ${Blue} $ssh1         $vma            $vla           $tra              $ssa$NC"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${CYAN}[01]${NC} • [SSH MANAGER]            ${CYAN}[10]${NC} • [CEK BANDWIDTH]"
echo -e "  ${CYAN}[02]${NC} • [VMESS MANAGER]          ${CYAN}[11]${NC} • [UPDATE SCRIPT]"
echo -e "  ${CYAN}[03]${NC} • [VLESS MANAGER]          ${CYAN}[12]${NC} • [DOMAIN GRATIS]"
echo -e "  ${CYAN}[04]${NC} • [TROJAN MANAGER]         ${CYAN}[13]${NC} • [HAPUS AKUN EXP]"
echo -e "  ${CYAN}[05]${NC} • [SSWS MANAGER]           ${CYAN}[14]${NC} • [SPEEDTEST]"
echo -e "  ${CYAN}[06]${NC} • [GANTI DOMAIN]           ${CYAN}[15]${NC} • [RUNNING]"
echo -e "  ${CYAN}[07]${NC} • [RENEW SERTIFIKAT]       ${CYAN}[16]${NC} • [REBOOT]"
echo -e "  ${CYAN}[08]${NC} • [CEK TRAFIK]             ${CYAN}[17]${NC} • [INFO]"
echo -e "  ${CYAN}[09]${NC} • [CEK PERFORMA]           ${CYAN}[18]${NC} • [ADD BOT TELEGRAM]"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "                     ⚡ SCRIPT PREMIUM BY EXCEPT STORE ⚡                 \E[0m"
echo -e "$COLOR1━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " [X]${NC} • [PRESS X TO EXIT]"
echo -e ""
echo -ne " Select menu : "; read opt
case $opt in
1) clear ; menussh ;;
2) clear ; menuv ;;
3) clear ; menul ;;
4) clear ; menut ;;
5) clear ; menus ;;
6) clear ; gantidomain ;;
7) clear ; renewsertifikat ;;
8) clear ; cek-trafik ;;
9) clear ; htop ;;
10) clear ; cek-bandwidth ;;
11) clear ; updatsc ;;
12) clear ; gratisbos ;;
13) clear ; xp ;;
14) clear ; cek-speed ;;
15) clear ; running ;;
16) clear ; reboot ;;
17) clear ; cat /root/log-install.txt ;;
18) clear ; bot ;;
0) clear ; menu ;;
x) exit ;;
*) clear ; menu ;;
esac
